[features]
seeds = false
skip-lint = false
[programs.devnet]
token_exchange = "2mcXtmhv184eihwhqxvoD41QWyuDm4DirpFwHkpCrxyM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/vc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
